name: Pull Request Build & Test

on:
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run eslint
        run: npx eslint .

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test


       
